# Know your exam  

## Strategy
For ISS examination Knowing the pattern of the examination is very important to prepare for the examination strategically. The candidate has to undergo 2 stages of selection where 1 stage is written examination and the 2nd stage is Viva-voce or interview. The written examination will be conducted for 1000 marks for ISS candidates. India Statistical Service candidates has to write objective and descriptive papers. Descriptive papers consist of short answer type and long answer type questions. The viva-voce or interview test is conducted for 200 marks. The candidates who are qualified in both the rounds are recruited.  

## ISS Exam Pattern  


|||||
|--- |--- |--- |--- |
|Sl.No|Paper|Marks|Duration|
|1|General English|100|3 hours|
|2|General Studies|100|3 hours|
|3|Statistics-I(Objective)|200|2 hours|
|4|Statistics-II(Objective)|200|2 hours|
|5|Statistics-III(Descriptive)|200|3 hours|
|6|Statistics-IV(Descriptive)|200|3 hours|  

The Written examination is conducted for 1000 marks which include 6 subjects. The time duration will be  3 hours for all 6 subjects.  

## Notification and Syllabus  

Usually notification for the exam is issued around April. All female candidates and candidates belong to SC/ST are not required to pay any fee. Exam will be usually in the month of June for 3 consecutive days.  
[Click Here to download the Syllabus](https://drive.google.com/file/d/1dsXAjQEbM76SIFc6_KxwAhLQAYpz2h0u/view?usp=sharing)   

Statistics I & II will be of Objective Type Questions (80 questions with maximum marks of 200 in each paper) to be attempted in 120 minutes.  

Statistics III will be of Descriptive Type having Short Answer/ Small Problems Questions (50%) and Long Answer and Comprehension problem questions (50%). At least one Short Answer and One Long Answer Question from each section are compulsory.  

In Statistics IV, there are FOURTEEN questions divided under SEVEN Sections. Candidate has to choose any TWO Sections and attempt the questions therein. All the Sections carry equal marks. That is in Statistics IV from the following subjects the candidates can choose any two and prepare for that. 
Operations Research and Reliability  
- Demography and Vital Statistics  
- Survival Analysis and Clinical Trial  
- Quality Control  
- Multivariate Analysis  
- Design and Analysis of Experiments  
- Computing with C and R 

Plan prepare well for the exam accordingly!!









 
       

